import type { TilemapProject, MapLayer, TileRect } from './types';

/**
 * ExportManager handles exporting the tilemap project to:
 * 1. A JSON file (custom format for import)
 * 2. A ready-to-use Phaser TileMap TypeScript class
 * 3. A Tiled-compatible JSON format (for use directly with Phaser's loader)
 */
export class ExportManager {
  /**
   * Export the entire project as a JSON file.
   */
  exportJSON(project: TilemapProject): void {
    const json = JSON.stringify(project, null, 2);
    this.downloadText(json, `${project.tileset?.name ?? 'tilemap'}.tilemap.json`, 'application/json');
  }

  /**
   * Export a ready-to-use Phaser TypeScript class.
   */
  exportPhaserClass(project: TilemapProject): void {
    const code = this.generatePhaserClass(project);
    const name = project.tileset?.name ?? 'Tilemap';
    this.downloadText(code, `${name}Tilemap.ts`, 'text/plain');
  }

  /**
   * Export as Tiled-compatible JSON that Phaser can load via scene.make.tilemap({ key }).
   * Uses a single spritesheet tileset with uniform tiles for Phaser compatibility.
   */
  exportTiledJSON(project: TilemapProject): void {
    const tiled = this.generateTiledJSON(project);
    const json = JSON.stringify(tiled, null, 2);
    const name = project.tileset?.name ?? 'tilemap';
    this.downloadText(json, `${name}.tiled.json`, 'application/json');
  }

  private downloadText(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  private generatePhaserClass(project: TilemapProject): string {
    const { config, tileset, layers } = project;
    const className = this.toPascalCase((tileset?.name ?? 'Tilemap') + 'Tilemap');
    const tilesetKey = tileset?.name ?? 'tileset';
    const tilesetFile = tileset?.imageFileName ?? 'tileset.png';

    const tilesConst = tileset?.tiles.map((t) => {
      const propName = this.toCamelCase(t.name);
      return `    ${propName}: { id: ${t.id}, x: ${t.x}, y: ${t.y}, width: ${t.width}, height: ${t.height} }`;
    }).join(',\n') ?? '';

    // Build per-layer data
    const layerCode = layers.map((layer) => {
      const grid = this.buildGrid(layer, config.mapWidth, config.mapHeight);
      const rows = grid.map((row) => `      [${row.join(', ')}]`).join(',\n');
      const safeLayerName = this.toCamelCase(layer.name);
      return `
    const ${safeLayerName}Data = [\n${rows}\n    ];
    const ${safeLayerName}Layer = map.createBlankLayer('${layer.name}', tileset, 0, 0, ${config.mapWidth}, ${config.mapHeight}, ${config.tileWidth}, ${config.tileHeight});
    if (${safeLayerName}Layer) {
      for (let row = 0; row < ${safeLayerName}Data.length; row++) {
        for (let col = 0; col < ${safeLayerName}Data[row].length; col++) {
          const tileIndex = ${safeLayerName}Data[row][col];
          if (tileIndex >= 0) {
            ${safeLayerName}Layer.putTileAt(tileIndex + 1, col, row);
          }
        }
      }
    }`;
    }).join('\n');

    return `// Generated by Phaser Tilemap Maker
// Drop this file into your Phaser project and import it.
//
// Usage in your Scene:
//   import { ${className} } from './${className}';
//
//   preload() {
//     ${className}.preload(this);
//   }
//   create() {
//     const map = ${className}.create(this);
//   }

export class ${className} {
  /** Key used to register the tileset image with Phaser's loader */
  static readonly TILESET_KEY = '${tilesetKey}';

  /** Path to the tileset image (update to match your asset path) */
  static readonly TILESET_URL = 'assets/${tilesetFile}';

  /** Map dimensions */
  static readonly MAP_WIDTH = ${config.mapWidth};
  static readonly MAP_HEIGHT = ${config.mapHeight};
  static readonly TILE_WIDTH = ${config.tileWidth};
  static readonly TILE_HEIGHT = ${config.tileHeight};

  /** Individual tile frame definitions from the tileset image */
  static readonly TILES = {
${tilesConst}
  } as const;

  /** Preload the tileset image — call from your Scene's preload() method */
  static preload(scene: Phaser.Scene): void {
    scene.load.image(this.TILESET_KEY, this.TILESET_URL);
  }

  /**
   * Create and return the tilemap — call from your Scene's create() method.
   * The tileset is registered using ${config.tileWidth}x${config.tileHeight} base tile size.
   */
  static create(scene: Phaser.Scene): Phaser.Tilemaps.Tilemap {
    const map = scene.make.tilemap({
      width: ${config.mapWidth},
      height: ${config.mapHeight},
      tileWidth: ${config.tileWidth},
      tileHeight: ${config.tileHeight},
    });

    const tileset = map.addTilesetImage(
      this.TILESET_KEY,
      undefined,
      ${config.tileWidth},
      ${config.tileHeight},
    )!;
${layerCode}
    return map;
  }
}
`;
  }

  private generateTiledJSON(project: TilemapProject): object {
    const { config, tileset, layers } = project;
    const tilesetName = tileset?.name ?? 'tileset';
    const tilesetFile = tileset?.imageFileName ?? 'tileset.png';

    // Build flat array data for each layer (Tiled uses 1-based tile IDs, 0 = empty)
    const tiledLayers = layers.map((layer) => {
      const grid = this.buildGrid(layer, config.mapWidth, config.mapHeight);
      const data = grid.flat().map((id) => id >= 0 ? id + 1 : 0);
      return {
        data,
        height: config.mapHeight,
        id: layers.indexOf(layer) + 1,
        name: layer.name,
        opacity: 1,
        type: 'tilelayer',
        visible: true,
        width: config.mapWidth,
        x: 0,
        y: 0,
      };
    });

    return {
      compressionlevel: -1,
      height: config.mapHeight,
      infinite: false,
      layers: tiledLayers,
      nextlayerid: layers.length + 1,
      nextobjectid: 1,
      orientation: 'orthogonal',
      renderorder: 'right-down',
      tiledversion: '1.10.0',
      tileheight: config.tileHeight,
      tilesets: [
        {
          columns: tileset ? Math.max(1, Math.floor(
            tileset.tiles.reduce((max, t) => Math.max(max, t.x + t.width), 0) / config.tileWidth
          )) : 1,
          firstgid: 1,
          image: tilesetFile,
          imageheight: tileset?.tiles.reduce((max, t) => Math.max(max, t.y + t.height), config.tileHeight) ?? config.tileHeight,
          imagewidth: tileset?.tiles.reduce((max, t) => Math.max(max, t.x + t.width), config.tileWidth) ?? config.tileWidth,
          margin: 0,
          name: tilesetName,
          spacing: 0,
          tilecount: tileset?.tiles.length ?? 0,
          tileheight: config.tileHeight,
          tilewidth: config.tileWidth,
        },
      ],
      tilewidth: config.tileWidth,
      type: 'map',
      version: '1.10',
      width: config.mapWidth,
    };
  }

  /** Build a 2D grid array (row x col) where value is tile ID or -1 for empty */
  private buildGrid(layer: MapLayer, mapWidth: number, mapHeight: number): number[][] {
    const grid: number[][] = Array.from({ length: mapHeight }, () =>
      new Array<number>(mapWidth).fill(-1)
    );
    for (const placed of layer.tiles) {
      if (placed.row >= 0 && placed.row < mapHeight &&
          placed.col >= 0 && placed.col < mapWidth) {
        grid[placed.row][placed.col] = placed.tileId;
      }
    }
    return grid;
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase());
  }

  private toCamelCase(str: string): string {
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }
}
